dist: trusty
sudo: required
language: go
go:
- 1.11
install:
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
script:
- make test
- make vendor-status
- make vet
- make build
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: OnT68PG9JnUO0tSI7nz0K1OJNMeudTVC6pUM6+WLkLbVzI8z4LWiplWWnCZZk1B/873t3AK6XVFuOnITaVlXS9VNkBINU3YdfXMzqF1iz76n+3O6zjZn7v0Wx51LllrbCE9ZUTF9MmxkcqzMnEGqtok9ydtMGc6+aIDs/sCbebX26/2ieioT/D4J84r9LUSCIZuQmGzJBu3FAwOzuT5m6gauXqtXFbfylZig1UPk2tFwPupr6NIv1pJPSeT3epVoLxlxPOanJSeUIokqHSUmkUmgc2Gw7xrsPFFLybJOUfektuIhNqCw8T8aGZRdmH21L+3UTT6rNcdNgfzcrNQAjwulN/oIz5B/zgPDoecZxr0WCQm6ysDkdF3VpuytTElsRDJhef7lqCb6SVeIQKSbJcJTD0Ofyh+yj8LtGmR6rhUaPpMRC1rQjb/vOQpOJN7WuRQLf3FEN3eSXDYB8gGFX0Z0CW58MqZ8dzpm1ik3s8bIuGzY4vmhVVAuStZA0XBglHVdRnR11JlwrDVGKsdcBU/tPCs//mK6vG7yGqOmzF6IXoswc7jz6iQLBGuAJWQBw2MQH7FiyfZlF7ySt5c/H3Ycwf3Qrdj2O8eMnCnwmPanlDgfQw5szTiVKgEP67draJXOPJCEHa9BV2gqQu7co/W67BFlU9uD2SWHUWeweSs=
  file: terraform-provider-purestorage
  on:
    repo: devans10/terraform-provider-purestorage
    tags: true
