dist: trusty
sudo: false
language: go
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: 1.9.x
  - go: 1.10.x
  - go: 1.11.x
  - go: tip
  allow_failures:
  - go: tip
before_install:
- go get github.com/mitchellh/gox
install:
- bash scripts/gogetcookie.sh
- go get github.com/kardianos/govendor
- go get github.com/mitchellh/gox
script:
- make test
- make vendor-status
- make vet
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="{{.OS}}/terraform-provider-purestorage"
  -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
- if [ "${LATEST}" = "true" ]; then sha1sum windows/terraform-provider-purestorage.exe
  > terraform-provider-purestorage.windows.sha1; tar -czf terraform-provider-purestorage.windows.tar.gz  windows/terraform-provider-purestorage.exe;
  fi
- if [ "${LATEST}" = "true" ]; then sha1sum darwin/terraform-provider-purestorage
  > terraform-provider-purestorage.darwin.sha1; tar -czf terraform-provider-purestorage.darwin.tar.gz  darwin/terraform-provider-purestorage;
  fi
- if [ "${LATEST}" = "true" ]; then sha1sum linux/terraform-provider-purestorage >
  terraform-provider-purestorage.linux.sha1; tar -czf terraform-provider-purestorage.linux.tar.gz  linux/terraform-provider-purestorage;
  fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bsIA+daTW4ZBy3u7tBdVOZmgCKrGie/Sm2AHRhEUpMuO90+g5Kajxd5pZRPCrhtmCuMcIzyrmoW+GDdhvQGTWXBFXXo+aPRNwlVaVKyQNv7BN7FTLA9CpV2Bmx4RNooD+DA2pmeERdl5XQh2YgzxX0RjIuwBn3gSDld3tSfSm8wu7jR0QLnb2AYdysLuNtXqkEBvqzafEA6ASZ8gBNNxt+mKFqqfQhetowpDYaLP2S9Zs1eaZfM9AKeXreT/3LOH8+fq+s+zbd6onktEgbHxG5bnHp024PWdIBVuVuAhoydDh7KqdSMyugh7Bv+7XmPtBUMck7R0EmOFMuSDwSbH5KhWUSayj2SpsgtOl/6kYaZyokz5fUs5A2OZXGl/NVCvGV48WE80Q9So0RO8pVAEYk67/FU7+sVacXOl0aydCRFJNe17qUYXTwOlQKXwGW53rIQN1BDVJBskkYzVkMpMydOqlGz9Iq1Kpd1gYppFFfqpH6/nMEeQKwRB6pGnfB+DIpVOXLwWl53rBrXQN7T1p+1F22YGA5gF5G6Xc8vYKY7Psfu3eOc2y9VBaFItoxgEUW8i1OCzlkmsdhRXCZ81cT53KzHGaZXVDTqZM1jOWVB0Hus8yK4JPkyLqU/MvqMQF7/AYaMQoGq+QqUUuGMBVgiRx2JJ1v1wJwfdClbV5u8=
  file:
  - terraform-provider-purestorage.windows.zip
  - terraform-provider-purestorage.windows.sha1
  - terraform-provider-purestorage.darwin.zip
  - terraform-provider-purestorage.darwin.sha1
  - terraform-provider-purestorage.linux.zip
  - terraform-provider-purestorage.linux.sha1
  on:
    repo: devans10/terraform-provider-purestorage
    tags: true
    condition: "$LATEST = true"
